
version: "3"
services:
    nginx:
        image: hub.c.163.com/public/nginx:1.2.1
        container_name: nginx
        volumes:
            - ./sites:/etc/nginx/conf.d
            - ./www:/var/www/html
        links:
            - php-fpm:php-fpm
        ports:
            - "8080:80"
    php-fpm:
        image: hub.c.163.com/library/php:7.1.9-fpm
        container_name: php-fpm
        volumes:
            - ./www:/var/www/html
        links:
            - mysql:mysql
            - redis:redis
    mysql:
        image: hub.c.163.com/library/mysql:5.6
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
        ports:
            - "3307:3306"
    redis:
        image: hub.c.163.com/public/redis:2.8.4
        container_name: redis
        expose:
            - "6379"
